apiVersion: v1
kind: ConfigMap
metadata:
  name: medical-qa-retrieval-dvc
data:
  dvc-config: |-
    [core]
        remote = gcsremote
    ['remote "gcsremote"']
        url = gs://{{ .Values.dvc.bucket }}/dvc
  dvc-yaml: |-
{{ .Values.dvc.yaml | indent 4 }}
  dvc-lock: |-
{{ .Values.dvc.lock | indent 4 }}
  artifacts-dvc: |-
{{ .Values.dvc.artifactsDvc | indent 4 }}
