apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: medical-qa-kserve
spec:
  predictor:
    minReplicas: {{ .Values.minReplicas }}
    containers:
      - name: kserve-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources | indent 10 }}
