apiVersion: v1
kind: Service
metadata:
  name: medical-qa-nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: medical-qa-nginx
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
