image:
  repository: ghcr.io/hinmq21/medical-qa-kserve-mock
  tag: latest
  pullPolicy: IfNotPresent

minReplicas: 0

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
